### ISSUE TITLE
error: [WinError 126 ] 

### ISSUE THREAD

**Issue by gerrardmai** [kfoynt/LocalGraphClustering#118]
from localgraphclustering import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gerra\Anaconda3\lib\site-packages\localgraphclustering\__init__.py", line 1, in <module>
    from .GraphLocal import GraphLocal
  File "C:\Users\gerra\Anaconda3\lib\site-packages\localgraphclustering\GraphLocal.py", line 10, in <module>
    from .cpp import *
  File "C:\Users\gerra\Anaconda3\lib\site-packages\localgraphclustering\cpp\__init__.py", line 33, in <module>
    _graphlib = load_library()
  File "C:\Users\gerra\Anaconda3\lib\site-packages\localgraphclustering\cpp\__init__.py", line 24, in load_library
    lib=ctypes.cdll.LoadLibrary(find_path())
  File "C:\Users\gerra\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\gerra\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

i found there are no libgraph.dll in graph_lib_test file?

**Comment by dgleich** [comment]
At the moment, we don't support windows.
